
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.3"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  branch = "master"

[[constraint]]
  name = "github.com/rifflock/lfshook"
  version = "1.7.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.6.7"

[[constraint]]
  name = "github.com/google/uuid"
  branch = "master"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "1.8.1"

[[constraint]]
  name = "github.com/robfig/cron"
  branch = "master"

[[constraint]]
  name = "github.com/selvatico/go-mocket"
  version = "1.0.4"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.7"
